# Generated by Django 3.2.5 on 2021-08-24 12:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departament', '0006_remove_departamentimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('price', models.FloatField()),
                ('date_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('time_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('available', models.BooleanField(default=True)),
                ('first_image', imagekit.models.fields.ProcessedImageField(upload_to='campaign/first/')),
                ('second_image', imagekit.models.fields.ProcessedImageField(upload_to='campaign/second/')),
                ('third_image', imagekit.models.fields.ProcessedImageField(upload_to='campaign/third/')),
                ('show', models.BooleanField(default=True)),
                ('about', ckeditor.fields.RichTextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('departament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departament.departament')),
            ],
        ),
    ]
