# Generated by Django 3.2.5 on 2021-08-24 12:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0006_remove_departamentimage_title'),
        ('campaign', '0002_auto_20210824_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-updated'], 'verbose_name': 'Kampaniya', 'verbose_name_plural': 'Kampaniyalar'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name='Ətraflı'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Davam Edir'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_interval',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Aktiv Olduğu Tarixlər'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departament.departament', verbose_name='Şöbə'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='first_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='campaign/first/', verbose_name='Əsas Şəkil'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='price',
            field=models.FloatField(verbose_name='Qiymət AZN ilə'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='second_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='campaign/second/', verbose_name='İkinci Şəkil'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Saytda Görünsün'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='third_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='campaign/third/', verbose_name='Üçüncü Şəkil'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='time_interval',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Aktiv Olduğu Saatlar'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Dəyişdirilmə Tarixi'),
        ),
    ]
