# Generated by Django 3.2.5 on 2021-07-28 17:37

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', imagekit.models.fields.ProcessedImageField(upload_to='departament/icons/')),
                ('slug', models.SlugField(blank=True, default='', max_length=100, unique=True)),
                ('about', ckeditor.fields.RichTextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartamentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('show_schedule', models.BooleanField(default=True)),
                ('monday_show', models.BooleanField(default=True)),
                ('monday_start', models.TimeField(default=datetime.time(9, 0))),
                ('monday_end', models.TimeField(default=datetime.time(17, 0))),
                ('tuesday_show', models.BooleanField(default=True)),
                ('tuesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('tuesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('wednesday_show', models.BooleanField(default=True)),
                ('wednesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('wednesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('thursday_show', models.BooleanField(default=True)),
                ('thursday_start', models.TimeField(default=datetime.time(9, 0))),
                ('thursday_end', models.TimeField(default=datetime.time(17, 0))),
                ('friday_show', models.BooleanField(default=True)),
                ('friday_start', models.TimeField(default=datetime.time(9, 0))),
                ('friday_end', models.TimeField(default=datetime.time(17, 0))),
                ('saturday_show', models.BooleanField(default=True)),
                ('saturday_start', models.TimeField(default=datetime.time(9, 0))),
                ('saturday_end', models.TimeField(default=datetime.time(17, 0))),
                ('sunday_show', models.BooleanField(default=False)),
                ('sunday_start', models.TimeField(default=datetime.time(9, 0))),
                ('sunday_end', models.TimeField(default=datetime.time(17, 0))),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepartamentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imagefile', imagekit.models.fields.ProcessedImageField(upload_to='departament/images/')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departament.departament')),
            ],
        ),
        migrations.AddField(
            model_name='departament',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departament.departamentschedule'),
        ),
    ]
