# Generated by Django 3.2.5 on 2021-07-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentimage',
            old_name='imagefile',
            new_name='image',
        ),
    ]
