# Generated by Django 3.2.5 on 2021-07-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0002_rename_imagefile_departamentimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='description',
            field=models.TextField(default='Bir aciqlama'),
            preserve_default=False,
        ),
    ]
