# Generated by Django 3.2.5 on 2021-07-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0005_auto_20210730_1033'),
        ('doctor', '0003_auto_20210730_1033'),
        ('appointment', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-updated'], 'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(verbose_name='Müraciət Tarixi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departament.departament', verbose_name='Müraciət Edilən Şöbə'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor', verbose_name='Müraciət Edilən Həkim'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email Ünvanı'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.TextField(verbose_name='Qeyd'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefon Nömrəsi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Baxıldı'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Müraciət Saatı'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Dəyişdirilmə Tarixi'),
        ),
    ]
