# Generated by Django 3.2.5 on 2021-08-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20210802_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='Müraciət Tarixi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Müraciət Saatı'),
        ),
    ]
