# Generated by Django 3.2.5 on 2021-08-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_rename_day_appointment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created'], 'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
    ]
