# Generated by Django 3.2.5 on 2021-07-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlImage',
            new_name='ArticleImage',
        ),
    ]
