# Generated by Django 3.2.5 on 2021-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210729_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=True, help_text='Bloqda göstərilsin mi?'),
        ),
    ]
