# Generated by Django 3.2.5 on 2021-07-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('blog', '0005_article_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Bloqda görünsünmü?'),
        ),
    ]
