# Generated by Django 3.2.5 on 2021-07-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210729_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-updated'], 'verbose_name': 'Məqalə', 'verbose_name_plural': 'Məqalələr'},
        ),
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Məqalə Şəkli', 'verbose_name_plural': 'Məqalə Şəkilləri'},
        ),
    ]
