# Generated by Django 3.2.5 on 2021-07-30 06:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20210730_1033'),
        ('blog', '0007_auto_20210729_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor', verbose_name='Müəllif'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='article/main_images/', verbose_name='Əsas Şəkil'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Dəyişdirilmə Tarixi'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='blog/article/images/', verbose_name='Şəkil Faylı'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(upload_to='blog/category/cover/', verbose_name='Qapaq Şəkli'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Dəyişdirilmə Tarixi'),
        ),
    ]
