# Generated by Django 3.2.5 on 2021-08-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='title',
        ),
    ]
