# Generated by Django 3.2.5 on 2021-07-28 17:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('show_schedule', models.BooleanField(default=True)),
                ('monday_show', models.BooleanField(default=True)),
                ('monday_start', models.TimeField(default=datetime.time(9, 0))),
                ('monday_end', models.TimeField(default=datetime.time(17, 0))),
                ('tuesday_show', models.BooleanField(default=True)),
                ('tuesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('tuesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('wednesday_show', models.BooleanField(default=True)),
                ('wednesday_start', models.TimeField(default=datetime.time(9, 0))),
                ('wednesday_end', models.TimeField(default=datetime.time(17, 0))),
                ('thursday_show', models.BooleanField(default=True)),
                ('thursday_start', models.TimeField(default=datetime.time(9, 0))),
                ('thursday_end', models.TimeField(default=datetime.time(17, 0))),
                ('friday_show', models.BooleanField(default=True)),
                ('friday_start', models.TimeField(default=datetime.time(9, 0))),
                ('friday_end', models.TimeField(default=datetime.time(17, 0))),
                ('saturday_show', models.BooleanField(default=True)),
                ('saturday_start', models.TimeField(default=datetime.time(9, 0))),
                ('saturday_end', models.TimeField(default=datetime.time(17, 0))),
                ('sunday_show', models.BooleanField(default=False)),
                ('sunday_start', models.TimeField(default=datetime.time(9, 0))),
                ('sunday_end', models.TimeField(default=datetime.time(17, 0))),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='doctor/image/')),
                ('profession', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=150)),
                ('facebook', models.URLField(max_length=300)),
                ('instagram', models.URLField(max_length=300)),
                ('whatsapp', models.URLField(max_length=300)),
                ('youtube', models.URLField(max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('departament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departament.departament')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.doctorschedule')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
