# Generated by Django 3.2.5 on 2021-07-29 08:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
