# Generated by Django 3.2.5 on 2021-07-30 06:33

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0005_auto_20210730_1033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0002_doctor_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name'], 'verbose_name': 'Həkim', 'verbose_name_plural': 'Həkimlər'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'verbose_name': 'Həkim İş Rejmi', 'verbose_name_plural': 'Həkim İş Rejimləri'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Haqqında Məlumat'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dərəcəsi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departament.departament', verbose_name='Şöbə'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook Linki'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='doctor/image/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram Linki'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Nömrəsi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profession',
            field=models.CharField(max_length=100, verbose_name='Vəzifəsi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.doctorschedule', verbose_name='İş Rejmi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Son Dəyişdirilmə Tarixi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi Hesabı'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Whatsapp Linki'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='youtube',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='YouTube Linki'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='friday_end',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Cümə Bitiş'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='friday_show',
            field=models.BooleanField(default=True, verbose_name='Cümə Rejmi Göstərilsin'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='friday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Cümə Başlanğıc'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='monday_end',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Bazar Ertəsi Bitmə'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='monday_show',
            field=models.BooleanField(default=True, verbose_name='Bazar Ertəsi Rejmi Göstərilsin'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='monday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Bazar Ertəsi Başlanğıc'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Şənbə Bitiş'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='saturday_show',
            field=models.BooleanField(default=True, verbose_name='Şənbə Rejmi Göstərilsin'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Şənbə Başlanğıc'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='show_schedule',
            field=models.BooleanField(default=True, verbose_name='İş rejmini Saytda Göstərilsin'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Bazar Bitiş'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='sunday_show',
            field=models.BooleanField(default=False, verbose_name='Bazar Rejmi Göstərilsin'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Bazar Başlanğıc'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Cümə Axşamı Bitiş'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='thursday_show',
            field=models.BooleanField(default=True, verbose_name='Cümə Axşamı Rejmi Göstərilsin'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Cümə Axşamı Başlanğıc'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Iş Rejmi Adı'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Çəşənbə Axşamı Bitiş'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='tuesday_show',
            field=models.BooleanField(default=True, verbose_name='Çərşənbə Axşamı Rejmi Göstərilsin'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Çərşənbə Axşamı Başlanğıc'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Dəyişdirilmə Tarixi'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Çəşənbə Bitiş'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='wednesday_show',
            field=models.BooleanField(default=True, verbose_name='Çəşənbə Rejmi Göstərilsin'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Çəşənbə Başlanğıc'),
        ),
    ]
