# Generated by Django 3.2.5 on 2021-08-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20210730_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='İl')),
                ('degree', models.CharField(max_length=50, verbose_name='Adı')),
                ('place', models.CharField(max_length=50, verbose_name='Təhsil Aldığı Yer')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
