# Generated by Django 3.2.5 on 2021-08-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctoreducation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoreducation',
            options={'ordering': ['year'], 'verbose_name': 'Təhsil', 'verbose_name_plural': 'Həkimin Təhsil Məlumatları'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Mail Ünvanı'),
        ),
    ]
